import './globals.css';

import type { Metadata } from 'next';

import { ThemeProvider } from '@/components/themeProvider';
import { inter } from '@/lib/fonts';

export const metadata: Metadata = {
  title: 'LinkLoom',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
